workflows:
  version: 2
  my_workflow:
    jobs:
      - build
      - docker_build_push: 
          requires: 
            - build
        
version: 2
jobs:
  build: &shared-config
    docker:
      - image: circleci/node:lts-fermium
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}-v1
            - dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}-v1
          
  docker_build_push:
    working_directory: /dockerapp
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Build application Docker image
          command: |
            docker build -t app . 
      - deploy:
          name: Publish application to docker hub
          command: |
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASS
            docker tag app $DOCKERHUB_USERNAME/$DOCKERHUB_APP_NAME:$CIRCLE_BUILD_NUM
            docker tag app $DOCKERHUB_USERNAME/$DOCKERHUB_APP_NAME:latest
            docker push $DOCKERHUB_USERNAME/$DOCKERHUB_APP_NAME:$CIRCLE_BUILD_NUM
            docker push $DOCKERHUB_USERNAME/$DOCKERHUB_APP_NAME:latest
      